[package]
name = "bencoding"
version = "0.1.0"
authors = ["Leonardo Hahn <leonnardo.hahn@gmail.com>"]
edition = "2018"

[lib]
name = "bencoding"
path = "src/lib.rs"

[[bin]]
name = "bencoding-main"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
log = "0.4.8"